stages:
  - test
  - init
  - validate

test:
  stage: test
  tags:
    - base
  script:
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - echo $PATH
    - which packer
    - packer version
    # - ls -l /usr/local/bin
    # - which packer
    # - packer version
    # - packer init photon5.pkr.hcl
    # - /usr/local/bin/packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

# test:
#   stage: test
#   image: 
#     name: hashicorp/packer:1.10
#     entrypoint:
#     - '/usr/bin/env'
#     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#   tags: 
#     - docker
#   script:
#     - echo $PATH
#     - ls -l /usr/local/bin
#     - which packer
#     - packer version

# init:
#   stage: init
#   tags: 
#     - base
#   script:
#     - /usr/local/bin/packer init .

# build:
#   stage: validate
#   tags: 
#     - base
#   script:
#     - /usr/local/bin/packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

