stages:
  - init
  - validate
  - build

init:
  stage: init
  tags:
    - docker
  image: 
    name: hashicorp/packer:1.10
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - packer --version
    - packer init photon5.pkr.hcl

validate:
  stage: validate
  tags: 
    - docker
  image: 
    name: hashicorp/packer:1.10
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

# build:
#   stage: validate
#   tags: 
#     - base
#   script:
#     - /usr/local/bin/packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

