stages:
  - test
  - init
  - build

test:
  stage: test
  tags: 
    - base
  script:
    - packer version

init:
  stage: init
  tags: 
    - base
  script:
    - packer init .

build:
  stage: build
  tags: 
    - base
  script:
    - packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

