stages:
  - test
  - build

test:
  stage: test
  tags: 
    - base
  script:
    - packer version

build:
  stage: build
  tags: 
    - base
  script:
    - packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

