stages:
  - test
  - init
  - validate

test:
  stage: test
  tags: 
    - docker
  image: hashicorp/packer:
  script:
    - /usr/local/bin/packer version

init:
  stage: init
  tags: 
    - docker
  script:
    - /usr/local/bin/packer init .

build:
  stage: validate
  tags: 
    - docker
  script:
    - packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

