stages:
  - validate
  - build

validate:
  stage: validate
  tags: 
    - docker
  image: 
    name: hashicorp/packer:1.10
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

# build:
#   stage: build
#   tags: 
#     - docker
#   image:
#     name: hashicorp/packer:1.10
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#   before_script:
#     - packer init photon5.pkr.hcl
#   script:
#     - packer build --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

