stages:
  - test
  - init
  - validate

test:
  stage: test
  tags: 
    - base
  script:
    - packer version

# init:
#   stage: init
#   tags: 
#     - base
#   script:
#     - /usr/local/bin/packer init .

# build:
#   stage: validate
#   tags: 
#     - base
#   script:
#     - /usr/local/bin/packer validate --var-file=photon5.auto.pkrvars.hcl photon5.pkr.hcl

